# Secret Rotation Configuration
rotation:
  schedule: "daily" # daily, weekly, monthly
  retry_attempts: 3
  timeout: 30

logging:
  level: "INFO"
  file: "logs/rotation.log"

providers:
  # We'll add provider configs here later

secrets:
  # We'll add secret configs here later
